FROM registry.access.redhat.com/ubi8/openjdk-17-runtime:latest

ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XshowSettings:vm"

ADD spark-operator/target/spark-operator-*.jar /deployments/spark-operator.jar

CMD ["/usr/bin/java", "-jar", "/deployments/spark-operator.jar"]
